name: Build ZMK firmware
on:
  workflow_dispatch:
  pull_request:
    paths: &build_trigger_paths
      - config/cradio.conf
      - config/cradio.keymap
      - config/west.yml
      - build.yaml
  push:
    paths: *build_trigger_paths

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
